export const translations = {
  en: {
    nav: { home: 'Home', features: 'Features', howItWorks: 'How It Works', systemOnline: 'System Online', startScanning: 'Start Scanning' },
    hero: {
      badge: '🔬 Powered by Claude AI',
      h1Line1: 'Detect Every Scam',
      h1Line2: 'Before It Reaches You',
      description: 'PhishGuard AI instantly analyzes calls, messages, links and websites using advanced artificial intelligence to protect you and your family from fraud.',
      cta1: 'Start Scanning Free →',
      cta2: '▶ Watch How It Works',
      trust1: '10,000+ Scams Detected',
      trust2: '99.2% Accuracy Rate',
      trust3: 'Free — No Sign Up Needed',
    },
    trust: { t1: 'AI-Powered Analysis', t2: '256-bit Secure', t3: 'Real-time Detection', t4: 'Always Free' },
    howItWorks: {
      title: 'How PhishGuard Works',
      subtitle: 'Three simple steps to stay protected',
      s1Title: 'Paste or Upload', s1Desc: 'Copy the suspicious message, link, or call transcript and paste it into PhishGuard.',
      s2Title: 'AI Analyzes', s2Desc: 'Our advanced AI engine scans for known scam patterns, phishing attempts, and fraud indicators.',
      s3Title: 'Get Result', s3Desc: 'Receive a detailed safety report with risk score, explanation, and voice guidance in seconds.',
    },
    stats: { totalScans: 'Total Scans', threats: 'Threats Found', safe: 'Safe', suspicious: 'Suspicious' },
    detection: {
      title: 'Start Scanning Now',
      tabs: { call: '📞 Call Detection', sms: '💬 SMS/Email', link: '🔗 Fake Link', website: '🌐 Website' },
      callPlaceholder: 'Paste the call transcript here or use the microphone...',
      smsPlaceholder: 'Paste the suspicious SMS or email content here...',
      linkPlaceholder: 'https://suspicious-link.com/verify',
      websitePlaceholder: 'https://suspicious-website.com',
      analyze: 'Analyze',
      loadSample: 'Load Sample',
      analyzing: 'AI is analyzing...',
    },
    voice: { speak: '🔊 Speak', stop: '⏹ Stop' },
    history: { title: 'Scan History', clearAll: 'Clear All', empty: 'No scans yet. Try analyzing something above!' },
    footer: { tagline: 'AI-powered protection for everyone', builtFor: 'Built to fight scams in India 🇮🇳' },
  },
  hi: {
    nav: { home: 'होम', features: 'सुविधाएँ', howItWorks: 'कैसे काम करता है', systemOnline: 'सिस्टम ऑनलाइन', startScanning: 'स्कैनिंग शुरू करें' },
    hero: {
      badge: '🔬 Claude AI द्वारा संचालित',
      h1Line1: 'हर स्कैम का पता लगाएं',
      h1Line2: 'इससे पहले कि वो आप तक पहुंचे',
      description: 'PhishGuard AI कॉल, मैसेज, लिंक और वेबसाइट का तुरंत विश्लेषण करता है ताकि आप और आपका परिवार धोखाधड़ी से सुरक्षित रहें।',
      cta1: 'मुफ्त स्कैनिंग शुरू करें →',
      cta2: '▶ देखें कैसे काम करता है',
      trust1: '10,000+ स्कैम का पता लगाया',
      trust2: '99.2% सटीकता दर',
      trust3: 'मुफ्त — साइन अप की जरूरत नहीं',
    },
    trust: { t1: 'AI-संचालित विश्लेषण', t2: '256-बिट सुरक्षित', t3: 'रियल-टाइम डिटेक्शन', t4: 'हमेशा मुफ्त' },
    howItWorks: {
      title: 'PhishGuard कैसे काम करता है',
      subtitle: 'सुरक्षित रहने के तीन आसान कदम',
      s1Title: 'पेस्ट या अपलोड करें', s1Desc: 'संदिग्ध मैसेज, लिंक या कॉल ट्रांसक्रिप्ट को कॉपी करके PhishGuard में पेस्ट करें।',
      s2Title: 'AI विश्लेषण करता है', s2Desc: 'हमारा उन्नत AI इंजन ज्ञात स्कैम पैटर्न और धोखाधड़ी संकेतकों की जांच करता है।',
      s3Title: 'परिणाम प्राप्त करें', s3Desc: 'सेकंडों में विस्तृत सुरक्षा रिपोर्ट, जोखिम स्कोर और वॉइस मार्गदर्शन प्राप्त करें।',
    },
    stats: { totalScans: 'कुल स्कैन', threats: 'खतरे मिले', safe: 'सुरक्षित', suspicious: 'संदिग्ध' },
    detection: {
      title: 'अभी स्कैनिंग शुरू करें',
      tabs: { call: '📞 कॉल डिटेक्शन', sms: '💬 SMS/ईमेल', link: '🔗 नकली लिंक', website: '🌐 वेबसाइट' },
      callPlaceholder: 'कॉल ट्रांसक्रिप्ट यहाँ पेस्ट करें या माइक्रोफोन का उपयोग करें...',
      smsPlaceholder: 'संदिग्ध SMS या ईमेल सामग्री यहाँ पेस्ट करें...',
      linkPlaceholder: 'https://suspicious-link.com/verify',
      websitePlaceholder: 'https://suspicious-website.com',
      analyze: 'विश्लेषण करें',
      loadSample: 'नमूना लोड करें',
      analyzing: 'AI विश्लेषण कर रहा है...',
    },
    voice: { speak: '🔊 बोलें', stop: '⏹ रुकें' },
    history: { title: 'स्कैन इतिहास', clearAll: 'सब साफ करें', empty: 'अभी तक कोई स्कैन नहीं। ऊपर कुछ विश्लेषण करके देखें!' },
    footer: { tagline: 'सभी के लिए AI-संचालित सुरक्षा', builtFor: 'भारत में स्कैम से लड़ने के लिए बनाया गया 🇮🇳' },
  },
} as const;

export type Language = 'en' | 'hi';
export type TranslationKey = typeof translations.en;
